baseURL = "https://koreanesia.eu.org/"
languageCode = "en-us"
title = "koreanesia"
theme = "z"
sectionPagesMenu = "main"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  post = ":slug"

[params]
  description = "Movie Collection"
  topdescription = "Watch Online Movie"
  toptitle = "koreanesia"
  contentBackgroundColor = "#fff"
  contentLinkColor = "#007bff"
  contentLinkHoverColor = "#0056b3"
  contentTextColor = "#212529"
  cookieConsent = false
  customBlockquoteStyle = true
  customCodeStyle = true
  customDateFormat = "Jan 2, 2006"
  faviconMsApplicationTileColor = "#da532c"
  faviconSafariPinnedTabColor = "#5bbad5"
  faviconThemeColor = "#ffffff"
  googleAnalytics = ""
  includeBootstrapJs = true
  navbarBackgroundColor = "#212529"
  navbarLinkColor = "rgba(255, 255, 255, 0.75)"
  navbarLinkHoverColor = "rgba(255, 255, 255, 1)"
  showPostSummary = true
  wrapperMaxWidth = ""
  [params.social.share]
    facebook = true
    linkedin = true
    twitter = true
    whatsapp = true
    email = true
    
[menu]
  [[menu.nav]]
  name = "Home"
  url = "/"
  weight = 1
  [[menu.nav]]
  name = "Drama"
  url = "/tags/drama"
  weight = 2
  [[menu.nav]]
  name = "Anime"
  url = "/tags/anime"
  weight = 3
  [[menu.nav]]
  name = "TV"
  url = "/tags/tv"
  weight = 4
  [[menu.nav]]
  name = "Movies"
  url = "/tags/movies"
  weight = 5
  
[author]
    name = "Admin"
    homepage = "https://koreanesia.eu.org/"
    bio = "Watch Online Movie"
    image = "https://user-images.githubusercontent.com/98423525/196342062-6b88c856-79ae-406c-ac9e-748574df19e5.png"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2
