name: Deploy to Pages
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.104.3"

      - name: Build Static HTML
        run: hugo

      - name: Install Dependencies
        run: npm install
